poethepoet/config.py

If there are Chinese characters in `pyproject.toml`, poe will fail to run tasks.  
I am not sure if other special characters might cause the same problem.
- Windows 10 (20H2, 10.0.19042.746); 64-bit; Simplified Chinese.
- Python 3.7.9 (AMD64)
> To explain beforehand, the Chinese word `你好` means "hello". And the word `作者`, mentioned in the next section, means "author". I choose these two words because they can exactly reproduce this issue.
```toml
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Author"]
[tool.poetry.dependencies]
python = "^3.7"
[tool.poetry.dev-dependencies]
poethepoet = "^0.9.0"
[tool.poe.tasks]
t1 = { shell = "echo Hello" }
t2 = { shell = "echo 你好" }
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
``` …

Open file with encoding="utf-8" specified

---

poethepoet/executor/base.py

When the running task is something infinite, let's say a web server, we should
be able to terminate it cleanly. To do that, we must forward the stop signal
to the subprocess. Previously the signal was caught by Poe, which is not desirable.
----
This PR makes sure, that you can stop poe tasks by Ctrl+C. I run into it when runnning a web server. I got a poe stacktrace instead of my projects stacktrace. This should fix it. Hope you like it. :slightly_smiling_face:

SIGINT forwarding to a running subprocess

---

README.rst
poethepoet/app.py
poethepoet/config.py
poethepoet/context.py
poethepoet/envfile.py
poethepoet/helpers.py
poethepoet/task/base.py
tests/fixtures/envfile/credentials.env
tests/fixtures/envfile/prod.env
tests/fixtures/envfile/pyproject.toml
tests/test_envfile.py
tests/unit/test_parse_env_file.py

Adds support for a new `envfile` option at global or task level. #22 
Includes an original lightweight parser for envfiles closely following bash syntax.

Support envfile task level and global option

---

README.rst
poethepoet/config.py
poethepoet/context.py
poethepoet/task/base.py
poethepoet/task/cmd.py
poethepoet/task/script.py
poetry.lock
pyproject.toml
tests/conftest.py
tests/fixtures/default_value/pyproject.toml
tests/test_default_value.py
tests/test_envfile.py

This is something I found necessary for my own use case. It allows similar semantics to `?=` variable assignment in make.
Setting an env var to a table with key default means the variable will only be set if not already provided by a lower precedence source such as the host shell or an env file. e.g.
```toml
[tool.poe.env]
PORT.default = "9001"
```
This PR build on top of #29
Documentation done, feature test TODO.

Add ability to declare default values for env vars in pyproject.toml

---

README.rst
poethepoet/config.py
poethepoet/task/shell.py
tests/conftest.py
tests/fixtures/shells_project/bad_interpreter.toml
tests/fixtures/shells_project/pyproject.toml
tests/fixtures/shells_project/shell_interpreter_config.toml
tests/test_script_tasks.py
tests/test_shell_task.py

Addresses #15 and #27 
The new shell executable resolution logic only considers the $SHELL env var as a hint (if it appears to match the target shell type), and never explicitly looks for WSL on windows. See included updates to documentation for more details.
Example of a shell task using fish shell:
```toml
[tool.poe.tasks.fibonacci]
help = "Output the fibonacci sequence up to 89"
interpreter = "fish"
shell = """
function fib --argument-names max n0 n1
if test $max -ge $n0
echo $n0
fib $max $n1 (math $n0 + $n1)
end
end
fib 89 1 1
"""
```
Note that there are a couple of significant limitations with the powershell integration that I don't know how to solve. Firstly when powershell starts it always prints some copyright boilerplate which is not really desirable for this use case, and …

Add ability to configure which type of shell to use for executing shell tasks

---

.gitignore
README.rst
poethepoet/app.py
poethepoet/config.py
poethepoet/context.py
poethepoet/exceptions.py
poethepoet/executor/poetry.py
poethepoet/plugin.py
poetry.lock
pyproject.toml
tests/conftest.py
tests/fixtures/poetry_plugin_project/empty_prefix/pyproject.toml
tests/fixtures/poetry_plugin_project/poetry.lock
tests/fixtures/poetry_plugin_project/pyproject.toml
tests/test_executors.py
tests/test_poetry_plugin.py

Based off of #32 by @ThatXliner and refactored a bit.
- Uses the new command structure support in Poetry 1.2 to register commands with poe as a prefix. Also gives users the option to remove this (in which case they need to be careful not to have tasks that collide with poetry commands), or set it something else like `"run "` or `'x "` etc.
- Uses the virtualenv from poetry directly rather than calling poetry again in the task subprocess.
- Uses the default verbosity level from poetry unless it's set in pyproject.toml
- Includes a best effort hack to make open ended CLI options work with cleo via monkey patching
- Includes some enhancements for testing code

Add poetry plugin

---

poetry.lock
pyproject.toml

Now that both pylint and astroid no longer have the cap on the python version it can be removed from poe as well.
Closes #43

Remove the upper bound on Python 4.0

---

README.rst
poethepoet/context.py
poethepoet/env/cache.py
poethepoet/env/manager.py
poethepoet/env/parse.py
poethepoet/env/template.py
poethepoet/executor/base.py
poethepoet/executor/poetry.py
poethepoet/executor/simple.py
poethepoet/executor/virtualenv.py
poethepoet/task/base.py
poethepoet/task/cmd.py
poethepoet/task/ref.py
poethepoet/task/script.py
poethepoet/task/sequence.py
poethepoet/task/shell.py
pyproject.toml
tests/fixtures/cmds_project/pyproject.toml
tests/fixtures/envfile_project/pyproject.toml
tests/test_cmd_tasks.py
tests/test_envfile.py
tests/test_executors.py
tests/unit/test_parse_env_file.py

Closes #38, also addresses #33 
- Major refactor of internal APIs for managing env vars
- Set POE_ACTIVE in PoeExecutor.__init__ instead of every implementation
- Fix issue caused by dependency on pypi in executor tests
---
Works for both global and task level env variables.
Example usage:
.. code-block:: toml
[tool.poe.tasks.serve]
serve.cmd = "flask run"
serve.env   = { FLASK_RUN_PORT = "${TF_VAR_service_port}" }

Add support for variable templating in configured env vars

---

poetry.lock
pyproject.toml

Besides removing support for python 3.6, the only breaking changes in tomli 2.0 are in the first parameter of `load`/`loads`: it can no longer be passed by keyword, and in the case of `load` it must be a binary file object.  Poe already does that, so no further changes are required.

Remove the upper bound on tomli 2.0

---

README.rst
poethepoet/config.py
poethepoet/plugin.py

Fixes #79 
Also:
- Make the plugin handle unexpected errors more gracefully
- Update doc for installing plugin for correct shell syntax

Fix poetry plugin crash on windows when outside of project

---

poethepoet/task/ref.py
pyproject.toml
tests/fixtures/sequences_project/pyproject.toml
tests/test_sequence_tasks.py

Fix bug to allow ref tasks to pass arguments again

---

README.rst

docs: use poe --group dev instead of poe --dev

---

poethepoet/virtualenv.py

This PR addresses  #119 for `cmd`  tasks that use the poetry executor. I found that, on Windows, a task like the following wasn't working:
```toml
[tool.poe.tasks]
"check-spelling" = "npx cspell README.md CHANGELOG.md"
```
Running the task on Windows is failing because `npx` does not exist, it's actually `npx.cmd`:
```
poetry run poe check-spelling
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
The problem seems to be that the fix for #119 was done in [`PoeExecutor.execute`](https://github.com/nat-n/poethepoet/blob/main/poethepoet/executor/base.py#L135), however this isn't called by the poetry executor since it calls `PoeExecutor._execute_cmd()` directly, bypassing the fix. I've confirmed that this PR works for my case.

win32: Resolve Executable to Absolute Path if not found in venv

---

poethepoet/task/cmd.py
tests/test_cmd_tasks.py
tests/test_envfile.py
tests/test_poe_config.py
tests/test_sequence_tasks.py

I found an issue related to #16 where, on Windows, a quoted token is being passed to the command still wrapped in quotes. This only happens on Windows because the `shelx.split(posix=False)` preserves them. You can verify this issue on Windows with the poethepoety `test-quick` task, which passes a quotes string to pytest and fails because the marker contains an invalid quote character:
```
Poe => pytest --cov=poethepoet -m "not slow"
ERROR: Wrong expression passed to '-m': "not slow": at column 1: unexpected character ""
```
I initially was seeing this with a call to cspell and have reproduced it with a small script / task.
```python
import sys
print(sys.argv)
```
```toml
[tool.poe.tasks.args]
cmd = "python args.py \"hello world\" \"some/glob/**/*.py\""
```
The results of running the …

cmd task: Strip quotes from token on Windows

---

docs/installation.rst

I was going through the guide and stumbled upon this. Shouldn't it generate a completion script for `poe` instead of `poetry`?

fix: zsh completion without oh-my-zsh

---

docs/conf.py
poethepoet/app.py
poethepoet/config.py
poethepoet/plugin.py
poethepoet/task/args.py
poethepoet/task/base.py
poethepoet/ui.py
pyproject.toml
tests/conftest.py
tests/fixtures/custom_config_project/tasks.json
tests/fixtures/custom_config_project/tasks.toml
tests/fixtures/poetry_plugin_project/with_prefix/poetry.lock
tests/fixtures/poetry_plugin_project/with_prefix/poetry.toml
tests/fixtures/poetry_plugin_project/with_prefix/pyproject.toml
tests/test_api.py
tests/test_cli.py
tests/test_poetry_plugin.py

I have a `pyproject.toml` within a packaged folder (with others in dynamic locations), and provide a global script which transparently runs `poe` inside a target folder to provide its tasks.
With this change, programs such as mine that wrap `poe` by using its main application class will automatically produce an accurate `USAGE` line.
Normal usage of `poe` will not see any change in the help message - regardless of whether it is running globally, via poetry, as a module, or as a poetry plugin.
`PoeThePoet.__call__` could pass its `internal` flag down to `ui.print_help()` in order to control this behavior, or an optional program name field could be added to the class instead.

Use sys.argv[0] for help message USAGE line in ui.print_help().

---

poethepoet/config.py
poethepoet/task/base.py
poethepoet/task/sequence.py
tests/fixtures/monorepo_project/subproject_2/pyproject.toml
tests/test_includes.py

Ensure that the tasks are in the dict-form before trying to assign a "cwd" to the definition.
This is related to issue #158 
Sorry no tests for it yet.  I'll come back and add those, if you think this fix is worthwhile.

Convert included string-form tasks

---

docs/index.rst
docs/tasks/options.rst
poethepoet/app.py
poethepoet/context.py
poethepoet/env/manager.py
tests/conftest.py
tests/fixtures/cwd_project/pyproject.toml
tests/fixtures/monorepo_project/pyproject.toml
tests/fixtures/monorepo_project/subproject_3/pyproject.toml
tests/test_cmd_tasks.py
tests/test_includes.py

For some tasks, it may be useful to use the working directory from which the task has been executed, since they may be meant to operate on some files that the user points them to. This commit introduces a special '$exec_cwd' value for the 'cwd' task option, which does exactly that. Existing use-cases are unaffected by this addition and work as usual.

Allow use of the original working directory for tasks

---

docs/tasks/task_types/switch.rst

`control.expr` is defined in the `build` task and `switch` is defined in `platform_dependent` task, so there is a discrepancy in definitions.
I fixed this by replacing `platform_dependent` with `build`.

Fix document of switch tasks

---

docs/guides/args_guide.rst

It is not totally obvious how to reference variables passed to a shell that uses a PowerShell interpreter. The trick is you need to access them as environment variables. I added a brief blurb on how to do this to the docs. 
I rebuilt the docs and reviewed my change visually:
The tip at the bottom is what I added.

📝 add information about referencing vars from PowerShell to docs

---

poethepoet/executor/base.py

The current implementation outputs an error `executable could not be found` when the cwd directory does not exist.
The error message is confusing, so I added an error when the cwd does not exist.
```toml
[tool.poe.tasks.cwd-ok]
cwd = ".github"
cmd = "echo ok"
[tool.poe.tasks.cwd-ng]
cwd = "notexist"
cmd = "echo ng"
```
**Ubuntu(WSL)**
```
$ poe cwd-ok
Poe => echo ok
ok
$ poe cwd-ng
Poe => echo ng
Poe the Poet - A task runner that works well with poetry.
version 0.24.1
Error: executable 'echo' could not be found using virtualenv '/home/kzrnm/poethepoet/.venv' 
USAGE
poe [-h] [-v | -q] [--root PATH] [--ansi | --no-ansi] task [task arguments]
....................................
```
**Windows(Git Bash)**
```
$ poe cwd-ok
Poe => echo ok
ok
$ poe cwd-ng
Poe => echo ng
Traceback (most recent …
```

Fix error message when the cwd directory does not exist

---

poethepoet/executor/base.py
poethepoet/executor/poetry.py
poethepoet/executor/virtualenv.py

poe cannot run `PoetryExecutor` if poetry is set as an alias instead of `$PATH`.
I want to skip `PoetryExecutor` when poetry is not found.

Skip PoetryExecutor if poetry is not found

---

poethepoet/helpers/command/__init__.py
tests/fixtures/cmds_project/pyproject.toml
tests/test_cmd_tasks.py

Fix faulty cmd tokenization 

---

poethepoet/task/script.py
poethepoet/task/switch.py
pyproject.toml
tests/fixtures/switch_project/pyproject.toml
tests/test_switch_task.py

Fixes #182 by making a switch task capture the contents of the case task for the next task to use.
Also tweak implementation of script tasks to make variable collisions less likely.

Make switch task work as expected with 'uses' option

---

docs/tasks/task_types/ref.rst
poethepoet/app.py
poethepoet/task/args.py
poethepoet/task/base.py
poethepoet/task/cmd.py
poethepoet/task/expr.py
poethepoet/task/ref.py
poethepoet/task/script.py
poethepoet/task/sequence.py
poethepoet/task/shell.py
poethepoet/task/switch.py
tests/fixtures/refs_project/pyproject.toml
tests/test_ref_task.py

Ref tasks can now parse named arguments and template the values into the invocation of the referenced task. Extra args (provided after `--` or all args if named arg configured) are appended to the invocation
Additional refactor:
- Add debug logging that is activated by setting the POE_DEBUG environment variable
- consolidate logic for getting extra args passed after `--`
- Remove extra_args argument from methods for task running in favour of always use 
invocation as the source of truth for CLI args
Related #196

Make args work as expected on ref tasks

---

poethepoet/task/shell.py

On Windows, I only see `Some dependencies may be missing from your system.` even though the value of `config_value` is `('posix',)`. This is because the type comparison is wrong, it checks that the tuple `('posix',)` is in `('posix', 'bash')`, instead of checking the string `posix`.
This PR fixes it by doing a set subset check.

Fixes Windows error message due to incorrect type comparison.

---

docs/poetry_plugin.rst

Hi there,
I have noticed that the following URL is broken on this page: https://poethepoet.natn.io/poetry_plugin.html
https://python-poetry.org/docs/master/plugins/#using-plugins
I have changed it to:
https://python-poetry.org/docs/main/plugins/#using-plugins
Have a nice day 😃 
Great tool btw!

Fix docs plugin link

---

poethepoet/config.py
poethepoet/plugin.py
tests/fixtures/poetry_plugin_project/empty_prefix/pyproject.toml
tests/fixtures/poetry_plugin_project/empty_prefix/tasks.toml
tests/test_poetry_plugin.py

Fixes https://github.com/nat-n/poethepoet/issues/199 by making the poetry plugin load tasks using PoeConfig to ensure included task files are loaded as usual.
Replaces #200

Allow poetry plugin with empty command prefix to run tasks included from another file

---

docs/guides/global_tasks.rst
docs/guides/index.rst
docs/index.rst
docs/installation.rst
poethepoet/__init__.py
poethepoet/completion/bash.py
poethepoet/completion/fish.py
poethepoet/completion/zsh.py
poethepoet/config.py
pyproject.toml

Completion scripts and list_tasks are not configurable to specify the executable name and respect the -C/--directory option.
fish and zsh completion scripts now understand when the -C/--directory option has been specified and will suggest tasks from the correct project.
The zsh completion script also generally handles passing multiple arguments.
Addresses #233

Document support for global tasks and improve completion scripts

---

docs/global_options.rst
poethepoet/context.py
poethepoet/executor/base.py
poethepoet/ui.py
tests/test_api.py
tests/test_cli.py
tests/test_executors.py
tests/test_includes.py
tests/test_poetry_plugin.py

Also:
- Tweak output style to be more similar to poetry/cleo
- Add debug output when creating an executor
- Streamline executor creation logic to be simpler

Add --executor CLI option to override the executor at runtime.

---

poethepoet/task/sequence.py
tests/test_ignore_fail.py

Fix handling of ignore_fail option in nested sequences. Fixes #252.

fix: Fix handling of ignore_fail option in nested sequences

---

.github/workflows/ci.yml
docs/installation.rst
poetry.lock
pyproject.toml
tests/test_script_tasks.py

Drop support for python 3.8 and start testing 3.13

chore: Drop support for python 3.8 and start testing 3.13

---

poethepoet/app.py
poethepoet/config/partition.py
poethepoet/config/primitives.py
poethepoet/options/__init__.py
poethepoet/options/annotations.py
poethepoet/task/args.py
poethepoet/task/base.py
poethepoet/task/shell.py

- Refactor PoeOptions parsing to validate complex data structures
- Improve validation and error reporting logic for args config
- Improve error handling in a few places

Various improvements to config validation logic and error handling in general

---

docs/guides/args_guide.rst
poethepoet/__init__.py
poethepoet/env/cache.py
poethepoet/options/__init__.py
poethepoet/task/args.py
poetry.lock
pyproject.toml

Also:
- Tweak envfile caching logic
- Improve validation coverage for args config
- Fix rstcheck errors and upgrade sphinx

fix: Make task autocompletion work again in sub-directories

---

docs/tasks/task_types/sequence.rst
poethepoet/task/sequence.py

fix: Explicitly disallow capture_stdout option on sequence tasks

---

.github/workflows/ci.yml
docs/tasks/task_types/cmd.rst
poethepoet/app.py
poethepoet/env/template.py
poethepoet/exceptions.py
poethepoet/helpers/command/__init__.py
poethepoet/helpers/command/ast.py
poethepoet/helpers/command/ast_core.py
poethepoet/task/cmd.py
tests/conftest.py
tests/helpers/command/test_ast.py
tests/test_cmd_param_expansion.py

Specifically cmd tasks may now use the following operations like in bash
- `:-` fallback value, e.g. ${AWS_REGION:-us-east-1}
- `:+` value replacement, e.g. ${AWESOME:+--awesome-mode}
This was done by adding AST parser support for Param Expansion operators
Also:
- Fix bug in param expansion logic for pure whitespace param values
- Add env paramater to PoeThePoet class to override os.environ for testing

feat: Make command parsing support operations on param expansions

---

poethepoet/config/config.py
poethepoet/plugin.py

Projects created with poetry >= 2.0 don't necessarily include a tool.poetry 
table in the pyproject.toml. Thus poethepoet cannot rely on the presence or 
absence of this table to tell whether it is appropriate to default to using 
the PoetryExecutor to run tasks with poetry's venv.
It seems the best remaining indicator is the content of the build-system which 
poetry still configures consistently, although this is less ideal.

fix: improve detection of poetry 2 projects

---

poethepoet/config/config.py
poethepoet/executor/poetry.py
poethepoet/plugin.py
pyproject.toml
tests/conftest.py
tests/test_poetry_plugin_v1.py
tests/test_poetry_plugin_v2.py

Fixes #270
- Create a PoeConfig once on plugin initialization, and reuse it in the command. This allows the plugin to find the config before the working directory is updated as a result of including the `--directory` option.
- Update the cleo monkeypatch to account for --directory and --project options taking an argument and being rewritten to precede the command.
Also:
- disable poetry plugins when calling the poetry CLI inside PoetryExecutor
- Duplicate poetry plugin tests to run with two poetry versions

fix: issues with argument parsing in poetry 2.0 plugin

---

poethepoet/app.py
poethepoet/ui.py
tests/test_cli.py

fixes #271
You can now pass a task name to the global `--help` option to display help for just that task.

feat: Support displaying help for a single task

---

docs/global_options.rst

Support for "uv" was added in #271. This change adds the uv executor to the documentation.
The executor is usually auto-detected. The documentation should reflect all executors.

Add the `uv` executor to the documentation

---

poethepoet/executor/uv.py

`uv` is installed via Snap on Ubuntu. Snap is a wrapper providing a safe environment for execution.
Snap symlinks all executable commands to it's binary.
* Called as `snap`: Snap CLI
* Called as a symlink from any other file: Execute the file in it's environment
The `UvExecutor` class resolved the path itself including any symlinks and eventually calls `/usr/bin/snap` instead of `/snap/bin/uv`. Snaps assumes a call to it's own CLI and fails.
With this patch, the shell will resolve the path and provide the correct "executed file" information (`$0` in a Bash script) to Snap.
fixes #282
Replace this text with a description of the changes proposed in this PR, including the motivation for these changes and a reference to any related GitHub issue or discussion.

fix: The UV executor exectures the wrong file

---

poethepoet/executor/base.py
poethepoet/executor/uv.py
pyproject.toml
tests/fixtures/uv_project/subproject/pyproject.toml
tests/fixtures/uv_project/subproject/uv.lock
tests/test_uv_executor.py

fixes #281
Replace this text with a description of the changes proposed in this PR, including the motivation for these changes and a reference to any related GitHub issue or discussion.

fix: Make UvExecutor set directory and project options on uv run

---

poethepoet/task/args.py
poethepoet/task/base.py
tests/fixtures/include_scripts_project/tasks.py
tests/fixtures/scripts_project/bad_content.toml

Also make error reporting for task args config validation more robust.

fix: always validate task args when loading config

---

docs/tasks/task_types/cmd.rst
docs/tasks/task_types/switch.rst
poethepoet/task/base.py
poethepoet/task/cmd.py
tests/fixtures/cmds_project/pyproject.toml
tests/test_cmd_tasks.py

Unmatched glob patterns will now be passed through to the task untouched, instead of being replaced with nothing.
The old behavior can be restored for a task be setting the new `empty_glob` option to "null" (like the nullglob option in bash). This option can also be set to "fail" to make the task execution fail with an error when an unmatched glob pattern is encountered.
In case a task fails in a way that might have been due to this breaking change then we write a warning message with a link to explain the breaking change.
Also:
- resolve relative paths for task level cwd early in the process.

feat!: Improve handling of unmatched glob patterns in cmd tasks
